# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccfeedback < Formula
  desc "Claude Code Feedback - Real-time linting feedback for AI code editors"
  homepage "https://jeremyrossi.com/ccfeedback/docs/"
  version "0.1.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jrossi/ccfeedback/releases/download/v0.1.7/ccfeedback_0.1.7_Darwin_x86_64.tar.gz"
      sha256 "9355b839f57e4bad5774950cd0af99371a4fb7cd07728b6bea6b33f5521ff370"

      def install
        bin.install "ccfeedback"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jrossi/ccfeedback/releases/download/v0.1.7/ccfeedback_0.1.7_Darwin_arm64.tar.gz"
      sha256 "700dee44e2f479685f0aec9507f088c8fab01a29e6e763858ea3476ed42010d7"

      def install
        bin.install "ccfeedback"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jrossi/ccfeedback/releases/download/v0.1.7/ccfeedback_0.1.7_Linux_x86_64.tar.gz"
      sha256 "9fa7afa7c1f9bd0f607414e9f5cb45c3a2ad27cce63c0408a21cd1c769a3fe1d"
      def install
        bin.install "ccfeedback"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jrossi/ccfeedback/releases/download/v0.1.7/ccfeedback_0.1.7_Linux_arm64.tar.gz"
      sha256 "5d6321e7cd295d0bf5f3a4a5c63398c5ce04407e5966c1bc9c857c1bc0db85e2"
      def install
        bin.install "ccfeedback"
      end
    end
  end

  test do
    system "#{bin}/ccfeedback", "--version"
  end
end
