# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccfeedback < Formula
  desc "Claude Code Feedback - Real-time linting feedback for AI code editors"
  homepage "https://jeremyrossi.com/ccfeedback/docs/"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jrossi/ccfeedback/releases/download/v0.2.0/ccfeedback_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "350827868eb4c9ea36bc263b040e36172bd231a5db351d36af0a3b02d2b07420"

      def install
        bin.install "ccfeedback"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jrossi/ccfeedback/releases/download/v0.2.0/ccfeedback_0.2.0_Darwin_arm64.tar.gz"
      sha256 "c646a51687d6688da0271e469f216d797c61c37e77414f7f7ac860db1535bf4d"

      def install
        bin.install "ccfeedback"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jrossi/ccfeedback/releases/download/v0.2.0/ccfeedback_0.2.0_Linux_x86_64.tar.gz"
      sha256 "2c062085e017691984bcd04bd91b48cc21728a6eba6e38c88aaca1b6eb055543"
      def install
        bin.install "ccfeedback"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jrossi/ccfeedback/releases/download/v0.2.0/ccfeedback_0.2.0_Linux_arm64.tar.gz"
      sha256 "811d72867ab7b94b371360b1aa73660efdef9cda57ad3a40201e7cdd37330b27"
      def install
        bin.install "ccfeedback"
      end
    end
  end

  test do
    system "#{bin}/ccfeedback", "--version"
  end
end
