# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccfeedback < Formula
  desc "Claude Code Feedback - Real-time linting feedback for AI code editors"
  homepage "https://github.com/jrossi/ccfeedback"
  version "0.1.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jrossi/ccfeedback/releases/download/v0.1.6/ccfeedback_0.1.6_Darwin_x86_64.tar.gz"
      sha256 "b9b9617d56340d8ba2420d40b8553933fbe20cb2577ffc5d0eecf2cc49a46b6e"

      def install
        bin.install "ccfeedback"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jrossi/ccfeedback/releases/download/v0.1.6/ccfeedback_0.1.6_Darwin_arm64.tar.gz"
      sha256 "a4360227a901c32f353e7759db9d81f406ebcd19118a8c02b8aaa5e615e83e69"

      def install
        bin.install "ccfeedback"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jrossi/ccfeedback/releases/download/v0.1.6/ccfeedback_0.1.6_Linux_x86_64.tar.gz"
      sha256 "87e84afb76f68b060b86e1a6c1ff0adde77f191e10bcd852d2a6b4a961163cb0"
      def install
        bin.install "ccfeedback"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jrossi/ccfeedback/releases/download/v0.1.6/ccfeedback_0.1.6_Linux_arm64.tar.gz"
      sha256 "e36e831adaba1d35a7bea2df74c85c08a09b8cd281633d7b0130d7eda85240fb"
      def install
        bin.install "ccfeedback"
      end
    end
  end

  test do
    system "#{bin}/ccfeedback", "--version"
  end
end
