# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gismo < Formula
  desc "Gismo - Real-time linting feedback for AI code editors"
  homepage "https://gismo.run/"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jrossi/gismo/releases/download/v0.3.0/gismo_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "39b23de5cdd72d72c13e148ae727f7febcc34a375e2743a3f42d80c8c6ad80c7"

      def install
        bin.install "gismo", "gismo-init", "gismo-show"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jrossi/gismo/releases/download/v0.3.0/gismo_0.3.0_Darwin_arm64.tar.gz"
      sha256 "80fa7029f84b1d317301aff7e023687675c0f99ba8860ce6934fa6edb85148c2"

      def install
        bin.install "gismo", "gismo-init", "gismo-show"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jrossi/gismo/releases/download/v0.3.0/gismo_0.3.0_Linux_x86_64.tar.gz"
      sha256 "87603c9d2caedb15b057e706c847a09c0a9c1a99286b94f6c1f2b0e7a0133f20"
      def install
        bin.install "gismo", "gismo-init", "gismo-show"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jrossi/gismo/releases/download/v0.3.0/gismo_0.3.0_Linux_arm64.tar.gz"
      sha256 "1ce50daf74ddd0e5332b5ae1b2b944595f13bb3f4e209bc35b3c94a9bfebc17b"
      def install
        bin.install "gismo", "gismo-init", "gismo-show"
      end
    end
  end

  test do
    system "#{bin}/gismo", "--version"
  end
end
