run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US

linters:
  enable:
    - bodyclose
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - gosec

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: cmd/
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0