baseURL = 'https://jrossi-claude.github.io/ccfeedback/'
languageCode = 'en-us'
title = 'CCFeedback Documentation'
theme = 'docsy'

[params]
github_repo = 'https://github.com/jrossi-claude/ccfeedback'
github_branch = 'main'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Documentation"
    url = "/docs/"
    weight = 10
  [[menu.main]]
    name = "CLI Reference"  
    url = "/docs/cli/"
    weight = 20
  [[menu.main]]
    name = "Library API"
    url = "/docs/library/"
    weight = 30
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/jrossi-claude/ccfeedback"
    weight = 50
